### ISSUE TITLE
Application getting crashed when cancelling the download 

### ISSUE THREAD

**Issue by arunap** [sgrebnov/cordova-plugin-background-download#13]
When I perform ' download.stop();' the application get crashed

**Comment by magude** [comment]
because download task need bind a receiver, when this task has been canceled, but the receiver and the indicator are still living.
the resolution is simple,that is to add "cordova.getActivity().unregisterReceiver(receiver);" above remove's line.
but code still has bug, download's task can't resume before app is restarted. let't try again...

**Comment by magude** [comment]
successed. can't resume download task is caused by "activDownloads" has data, clearing the map is OK.

**Comment by NickToropov** [comment]
Hi @arunap, we've made a number of improvements recently that fix this issue too. 

I'll close it for now but feel free to reopen it if you have any questions.
